sudo: required


language: java

jdk: oraclejdk8

services:
  - docker

before_install:
  - bash install-arx.sh

after_success:
  - bash <(curl -s https://raw.githubusercontent.com/sesam-community/guidelines/master/after_success.sh)